// db_service.proto

syntax = "proto3";

package db;

service Database {
    rpc ExecuteQuery (Query) returns (Response);
}

// Новое перечисление для операций
enum Operation {
    UNKNOWN_OPERATION = 0; // Добавьте необходимые операции
    SET_OP = 1;
    GET_OP = 2;
    DEL_OP = 3;
    GET_KEYS_OP = 4;
    // и так далее...
}

message Token {
    string type = 1;
    string value = 2;
}

message Query {
    Operation operation = 1;
    repeated Token tokens = 2;
}

message Response {
    bool success = 1;
    string message = 2;
    // Добавьте поля, которые вам нужны для передачи данных обратно клиенту
}
