// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: db_service.proto

#include "db_service.pb.h"
#include "db_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace db {

static const char* Database_method_names[] = {
  "/db.Database/ExecuteQuery",
};

std::unique_ptr< Database::Stub> Database::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Database::Stub> stub(new Database::Stub(channel, options));
  return stub;
}

Database::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ExecuteQuery_(Database_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Database::Stub::ExecuteQuery(::grpc::ClientContext* context, const ::db::Query& request, ::db::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::db::Query, ::db::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExecuteQuery_, context, request, response);
}

void Database::Stub::async::ExecuteQuery(::grpc::ClientContext* context, const ::db::Query* request, ::db::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::db::Query, ::db::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteQuery_, context, request, response, std::move(f));
}

void Database::Stub::async::ExecuteQuery(::grpc::ClientContext* context, const ::db::Query* request, ::db::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::db::Response>* Database::Stub::PrepareAsyncExecuteQueryRaw(::grpc::ClientContext* context, const ::db::Query& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::db::Response, ::db::Query, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExecuteQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::db::Response>* Database::Stub::AsyncExecuteQueryRaw(::grpc::ClientContext* context, const ::db::Query& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecuteQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

Database::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::db::Query, ::db::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::db::Query* req,
             ::db::Response* resp) {
               return service->ExecuteQuery(ctx, req, resp);
             }, this)));
}

Database::Service::~Service() {
}

::grpc::Status Database::Service::ExecuteQuery(::grpc::ServerContext* context, const ::db::Query* request, ::db::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace db

